### ISSUE TITLE
Dataset Google Link Access Denied

### ISSUE THREAD

**Issue by Erasmo1015** [yidingjiang/love#3]
Hi,

The link for dataset mentioned in "Additionally, download the datafiles from this [Google Drive link] and place them in the root love/ directory" cannot be accessed. May I ask for the access to the dataset?
![屏幕截图 2024-10-04 191930](https://github.com/user-attachments/assets/4ced5c97-07ef-42a2-a9a1-8bbe28a08069)

Thanks!

**Comment by yidingjiang** [comment]
Hi,

Sorry for the inconvenience. There was some mixed up with the google drive. We will update the README shortly but please use this [link](https://drive.google.com/drive/folders/1ZWZHnzIF-kQezy99-jWVBqToPWKxeTWX?usp=drive_link) for now.

**Comment by Erasmo1015** [comment]
Hi,

Thank you! I was able to download the world3d.tar.gz successfully. I look forward to seeing compile.tar.gz and checkpoints.tar.gz updated soon.

**Comment by yidingjiang** [comment]
Those two files are already included in the repo so you don't need to download them separately. This is the only big file so we had to put it on google drive.

**Comment by Erasmo1015** [comment]
Thanks. I can see those files in the repo now.
